version: '3'
services:
  web:
      build:
        context: ./php
        dockerfile: Dockerfile
      container_name: webserver
      depends_on:
      - database
      volumes:
       - ./php:/var/www/html/
      ports:
       - 3333:80
  database:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: mysql9
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: Complaint_Portal
        MYSQL_USER: newuser
        MYSQL_PASSWORD: newword
      ports:
        - 6033:3306
      volumes:
        - db:/var/lib/mysql
 volumes:
   db:
